# Generated by Django 4.2.5 on 2023-10-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_lead'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lead',
            table='lead',
        ),
    ]
