# Generated by Django 4.2.5 on 2023-10-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_lead_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lead',
            table=None,
        ),
    ]
