# Generated by Django 4.2.5 on 2023-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_leads_delete_customer_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(default='Default Name', max_length=255)),
                ('stage', models.CharField(default='Default Stage', max_length=255)),
                ('activity', models.CharField(default='Default Activity', max_length=255)),
                ('client', models.CharField(default='Default Client', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('responsible', models.CharField(default='Default Responsible', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_journey', models.CharField(default='Default Journey', max_length=255)),
            ],
        ),
    ]
